// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8QOcVecURiY7-riqQKoobcHpdeVnvZIw',
    appId: '1:365959265240:web:8a8d3d2bdcc02e855890ad',
    messagingSenderId: '365959265240',
    projectId: 'smart-snapper-7a290',
    authDomain: 'smart-snapper-7a290.firebaseapp.com',
    storageBucket: 'smart-snapper-7a290.appspot.com',
    measurementId: 'G-55BM89CQCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsBefg_tQ9VphoKHQTDr8bMT-GwFxrSlU',
    appId: '1:365959265240:android:d60d6b224d4c5f635890ad',
    messagingSenderId: '365959265240',
    projectId: 'smart-snapper-7a290',
    storageBucket: 'smart-snapper-7a290.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqv0jCbMl5Q-sQ6isjD0hhY_h5JFgsFzk',
    appId: '1:365959265240:ios:190ad405bc57e6c65890ad',
    messagingSenderId: '365959265240',
    projectId: 'smart-snapper-7a290',
    storageBucket: 'smart-snapper-7a290.appspot.com',
    iosBundleId: 'dev.flutterexplained.webrtc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqv0jCbMl5Q-sQ6isjD0hhY_h5JFgsFzk',
    appId: '1:365959265240:ios:dcb665968b5012905890ad',
    messagingSenderId: '365959265240',
    projectId: 'smart-snapper-7a290',
    storageBucket: 'smart-snapper-7a290.appspot.com',
    iosBundleId: 'dev.flutterexplained.webrtcTutorial',
  );
}
